/**
 * Build-time script: walks the repo's `skills/`, reads `sources.json`
 * and the `package.json` version, and writes `src/payload.generated.ts`
 * with the whole payload inlined as a JSON literal so it compiles into the
 * standalone binary. `node:` builtins only — Bun is just the runner.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import type {
  EmbeddedPayload,
  EmbeddedSkill,
  Marketplace,
  Source,
  Workspace,
} from "../src/types";

// scripts/embed-payload.ts -> scripts -> repo root. The CLI is the repo, so the
// payload (`skills/`, `sources.json`) and the package live at the same level.
const scriptDir = fileURLToPath(new URL(".", import.meta.url));
const repoRoot = join(scriptDir, "..");
const cliDir = repoRoot;

/** Recursively collect every file under `dir`, keyed by path relative to `base`. */
function collectFiles(dir: string, base: string): { path: string; contents: string }[] {
  const out: { path: string; contents: string }[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...collectFiles(full, base));
    } else if (entry.isFile()) {
      out.push({
        path: relative(base, full),
        contents: readFileSync(full, "utf8"),
      });
    }
  }
  return out;
}

function readSkills(): EmbeddedSkill[] {
  const skillsRoot = join(repoRoot, "skills");
  const skills: EmbeddedSkill[] = [];
  for (const entry of readdirSync(skillsRoot, { withFileTypes: true })) {
    // Only directories at the top level are skills; ignore stray files.
    if (!entry.isDirectory()) continue;
    const skillDir = join(skillsRoot, entry.name);
    skills.push({
      name: entry.name,
      files: collectFiles(skillDir, skillDir),
    });
  }
  // Stable ordering so the generated file is deterministic.
  skills.sort((a, b) => a.name.localeCompare(b.name));
  return skills;
}

function readSources(): { marketplaces: Marketplace[]; sources: Source[]; workspace?: Workspace } {
  const raw = readFileSync(join(repoRoot, "sources.json"), "utf8");
  const parsed = JSON.parse(raw) as { marketplaces: Marketplace[]; sources: Source[]; workspace?: Workspace };
  return { marketplaces: parsed.marketplaces, sources: parsed.sources, workspace: parsed.workspace };
}

function readVersion(): string {
  const raw = readFileSync(join(cliDir, "package.json"), "utf8");
  return (JSON.parse(raw) as { version: string }).version;
}

const { marketplaces, sources, workspace } = readSources();
const payload: EmbeddedPayload = {
  version: readVersion(),
  skills: readSkills(),
  marketplaces,
  sources,
  ...(workspace ? { workspace } : {}),
};

const banner =
  "// AUTO-GENERATED by scripts/embed-payload.ts — do not edit by hand.\n" +
  "// Regenerate with `bun run embed`. This file is git-ignored.\n";
const body =
  'import type { EmbeddedPayload } from "./types";\n\n' +
  `export const EMBEDDED_PAYLOAD: EmbeddedPayload = ${JSON.stringify(payload, null, 2)};\n`;

const outPath = join(cliDir, "src", "payload.generated.ts");
writeFileSync(outPath, banner + body, "utf8");

console.log(
  `Wrote ${relative(cliDir, outPath)} — ${payload.skills.length} skills, ` +
    `${payload.marketplaces.length} marketplaces, ${payload.sources.length} sources.`,
);
